### ISSUE TITLE
adjective.exc: The following pairs are not adjectives at all

### ISSUE THREAD

**Issue by avostryakov** [emorynlp/morphological_analysis#2]
Please, check the following pairs:

assaulter assaulter
attacker attacker
backer backer
bargainer bargainer
beater beater
biter biter
boner boner
bother bother
bounder bounder
bower bower
broadcaster broadcaster
brooder brooder
burster burster
buster buster
canter canter
caster caster
coder coder
costumer costumer
counterfeiter counterfeiter
cracker cracker
crasher crasher
creamer creamer
customer customer
darndest darned
dealer dealer
deserter deserter
dimer dimer
downer downer
dresser dresser
easter easter
edger edger
feller feller
flasher flasher
folder folder
foreigner foreigner
forest forest
founder founder
goer goer
goner goner
grader grader
grounder grounder
grouper grouper
guest guest
halter halter
header header
homer homer
hunger hunger
insider insider
interest interest
jointer jointer
lander lander
layer layer
left-hander left-hander
left-winger left-winger
liter liter
loather loather
loner loner
lowlander lowlander
mainer mainer
maligner maligner
mariner mariner
matter matter
milker milker
minter minter
miser miser
mocker mocker
modeler modeler
multiplexer multiplexer
muster muster
northeasterner northeasterner
norther norther
northerner northerner
old-timer old-timer
oliver oliver
opener opener
outsider outsider
overcomer overcomer
overnighter overnighter
owner owner
part-timer part-timer
passer passer
paster paster
pater pater
pearler pearler
pedaler pedaler
peter peter
plumber plumber
polisher polisher
porter porter
poster poster
presenter presenter
pretender pretender
primer primer
printer printer
privateer privateer
prompter prompter
puffer puffer
recorder recorder
renter renter
retailer retailer
right-hander right-hander
right-winger right-winger
roaster roaster
rusher rusher
salter salter
sampler sampler
scraper scraper
seconder seconder
signaler signaler
signer signer
skewer skewer
slaver slaver
sneaker sneaker
snuffer snuffer
solder solder
songwriter songwriter
southerner southerner
spreader spreader
springer springer
stapler stapler
starer starer
stocker stocker
stretcher stretcher
submariner submariner
swagger swagger
teenager teenager
teetotaler teetotaler
tester tester
toper toper
trader trader
trimer trimer
vest vest
waster waster
wholesaler wholesaler

**Comment by avostryakov** [comment]
I'm sorry. Some words can be adjectives. We are re-checking it now. I'll post a corrected list a little later.

**Comment by avostryakov** [comment]
We re-checked the list above and here is correct list of non-adjectives:
assaulter
attacker
backer
bargainer
beater
biter
boner
bother
bounder
bower
broadcaster
brooder
burster
buster
canter
caster
coder
costumer
counterfeiter
cracker
crasher
creamer
customer
darndest
dealer
deserter
dimer
downer
dresser
easter
edger
flasher
folder
foreigner
forest
founder
goer
goner
grader
grounder
grouper
header
homer
hunger
insider
interest
jointer
lander
layer
left-hander
left-winger
liter
loner
lowlander
mainer
maligner
mariner
matter
milker
minter
miser
mocker
modeler
multiplexer
muster
northeasterner
norther
northerner
old-timer
oliver
opener
outsider
overcomer
overnighter
owner
part-timer
passer
paster
pater
pearler
pedaler
peter
plumber
polisher
porter
poster
presenter
pretender
primer
printer
privateer
puffer
recorder
renter
retailer
right-hander
right-winger
roaster
rusher
salter
sampler
scraper
seconder
signaler
signer
skewer
slaver
sneaker
snuffer
solder
songwriter
southerner
spreader
springer
stapler
starer
stocker
stretcher
submariner
swagger
teenager
teetotaler
tester
toper
trader
trimer
vest
waster
wholesaler

**Comment by jdchoi77** [comment]
This looks good to me; could you please make a pull request including these?  Thanks.

**Comment by avostryakov** [comment]
Yes. See a new PR together with filtered adverb.base

**Comment by jdchoi77** [comment]
Manually merged.
